name: grassrootsapostles
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26879
title: Grassroots Apostles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#74565b'
    - '#1c1210'
    - '#97c0ec'
    - '#fef2f0'
    - '#e4297c'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
