name: grassrootsapostles
favicon: null
layout_spectrum: 0.28453657147474587
typography_spectrum: 0.2072316943667829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4282365129329264
  lightness: 0.9114998413715512
  saturation: 0.44519353029318154
  rhythmicContrast: 0.034212934551760554
purpose: []
